#server:
#  port: 8881
#
##person:
##  name: tom
##  age: 11
##  birth: 2022/1/2
##  list:
##    - 11
##    - 22
##    - 33
##  map: {k1:v1, k2:v2}
##  dog:
##    name: 狗子
#
## 指定使用哪一个文档快
#spring:
#  profiles:
#    active: prod
#---
#
#server:
#  port: 8882
#spring:
#  profiles: dev
#---
#
#server:
#  port: 8883
#
#spring:
#  profiles: prod